spring:
  application:
    name: bear-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bear_ai_code_mother
    username: root
    password: your-password
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 10000
      ttl: 3600
      connect-timeout: 5000
      jedis:
        pool:
          max-active: 20
          max-wait: 5000
          max-idle: 10
          min-idle: 2
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.mabear.bearaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name

