spring:
  application:
    name: bear-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bear_ai_code_mother
    username: root
    password: root
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.mabear.bearaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
