spring:
  application:
    name: bear-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bear_ai_code_mother
    username: root
    password: root
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.mabear.bearaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
