spring:
  application:
    name: bear-ai-code-screenshot
  profiles:
    active: local
server:
  port: 8126
  servlet:
    context-path: /api
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: your-region
    bucket: your-bucket-name
# Dubbo
dubbo:
  registry:
    address: nacos://host.docker.internal:8848
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 60000
  provider:
    timeout: 60000